def names():
  return {
    'id':  ['Id'],
    'out': ['SalePrice'],
    'cts': ['LotFrontage','LotArea','YearBuilt','YearRemodAdd','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','BsmtFullBath','BsmtHalfBath','FullBath','HalfBath','BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd','Fireplaces','GarageYrBlt','GarageCars','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch','ScreenPorch','PoolArea','MiscVal','YrSold'],
    'ord': ['LotShape','Utilities','LandSlope','OverallQual','OverallCond','ExterQual','ExterCond','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','HeatingQC','KitchenQual','Functional','FireplaceQu','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC'],
    'cat': ['MSSubClass','MSZoning','Street','Alley','LandContour','LotConfig','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','Foundation','Heating','CentralAir','Electrical','GarageType','Fence','MiscFeature','MoSold','SaleType','SaleCondition']
    }
  return

def cats():
  categories = {
    '3SsnPorch': [],
    'MasVnrType': ['brkcmn','brkface','cblock','none','stone','nan'],
    'LotConfig': ['inside','corner','culdsac','fr2','fr3','nan'],
    'BsmtUnfSF': [],
    'GarageQual': ['ex','gd','ta','fa','po','na','nan'],
    'Exterior1st': ['asbshng','asphshn','brkcomm','brkface','cblock','cemntbd','hdboard','imstucc','metalsd','other','plywood','precast','stone','stucco','vinylsd','wd sdng','wdshing','nan'],
    'GarageFinish': ['fin','rfn','unf','na','nan'],
    '2ndFlrSF': [],
    'HalfBath': [],
    'Utilities': ['allpub','nosewr','nosewa','elo','nan'],
    'OverallCond': ['10','9','8','7','6','5','4','3','2','1','nan'],
    'LotArea': [],
    'Fence': ['gdprv','mnprv','gdwo','mnww','na','nan'],
    'Electrical': ['sbrkr','fusea','fusef','fusep','mix','nan'],
    'SalePrice': [],
    'BsmtQual': ['ex','gd','ta','fa','po','na','nan'],
    'SaleCondition': ['normal','abnorml','adjland','alloca','family','partial','nan'],
    'HouseStyle': ['1story','1.5fin','1.5unf','2story','2.5fin','2.5unf','sfoyer','slvl','nan'],
    'GrLivArea': [],
    'YearRemodAdd': [],
    'SaleType': ['wd','cwd','vwd','new','cod','con','conlw','conli','conld','oth','nan'],
    'MasVnrArea': [],
    'Foundation': ['brktil','cblock','pconc','slab','stone','wood','nan'],
    'ExterCond': ['ex','gd','ta','fa','po','nan'],
    'BsmtFullBath': [],
    'BsmtCond': ['ex','gd','ta','fa','po','na','nan'],
    'HeatingQC': ['ex','gd','ta','fa','po','nan'],
    'LotFrontage': [],
    'MiscVal': [],
    'CentralAir': ['n','y','nan'],
    'BsmtExposure': ['gd','av','mn','no','na','nan'],
    'OverallQual': ['10','9','8','7','6','5','4','3','2','1','nan'],
    'KitchenAbvGr': [],
    'BsmtFinSF1': [],
    'LotShape': ['reg','ir1','ir2','ir3','nan'],
    'BsmtHalfBath': [],
    'TotalBsmtSF': [],
    'BsmtFinSF2': [],
    'TotRmsAbvGrd': [],
    'MiscFeature': ['elev','gar2','othr','shed','tenc','na','nan'],
    'PavedDrive': ['y','p','n','nan'],
    'OpenPorchSF': [],
    'LandSlope': ['gtl','mod','sev','nan'],
    'GarageYrBlt': [],
    'PoolArea': [],
    'FullBath': [],
    'YrSold': [],
    'ScreenPorch': [],
    'Exterior2nd': ['asbshng','asphshn','brk cmn','brkface','cblock','cmentbd','hdboard','imstucc','metalsd','other','plywood','precast','stone','stucco','vinylsd','wd sdng','wd shng','nan'],
    'Heating': ['floor','gasa','gasw','grav','othw','wall','nan'],
    'MSSubClass': ['20','30','40','45','50','60','70','75','80','85','90','120','150','160','180','190','nan'],
    'PoolQC': ['ex','gd','ta','fa','na','nan'],
    'WoodDeckSF': [],
    '1stFlrSF': [],
    'YearBuilt': [],
    'KitchenQual': ['ex','gd','ta','fa','po','nan'],
    'BsmtFinType2': ['glq','alq','blq','rec','lwq','unf','na','nan'],
    'BsmtFinType1': ['glq','alq','blq','rec','lwq','unf','na','nan'],
    'Condition2': ['artery','feedr','norm','rrnn','rran','posn','posa','rrne','rrae','nan'],
    'Condition1': ['artery','feedr','norm','rrnn','rran','posn','posa','rrne','rrae','nan'],
    'GarageType': ['2types','attchd','basment','builtin','carport','detchd','na','nan'],
    'LandContour': ['lvl','bnk','hls','low','nan'],
    'RoofMatl': ['clytile','compshg','membran','metal','roll','tar&grv','wdshake','wdshngl','nan'],
    'Neighborhood': ['blmngtn','blueste','brdale','brkside','clearcr','collgcr','crawfor','edwards','gilbert','idotrr','meadowv','mitchel','names','noridge','npkvill','nridght','nwames','oldtown','swisu','sawyer','sawyerw','somerst','stonebr','timber','veenker','nan'],
    'Fireplaces': [],
    'BedroomAbvGr': [],
    'MoSold': ['1','2','3','4','5','6','7','8','9','10','11','12','nan'],
    'BldgType': ['1fam','2fmcon','duplex','twnhse','twnhs','nan'],
    'ExterQual': ['ex','gd','ta','fa','po','nan'],
    'Functional': ['typ','min1','min2','mod','maj1','maj2','sev','sal','nan'],
    'Alley': ['grvl','pave','na','nan'],
    'RoofStyle': ['flat','gable','gambrel','hip','mansard','shed','nan'],
    'Street': ['grvl','pave','nan'],
    'LowQualFinSF': [],
    'GarageArea': [],
    'MSZoning': ['a','c','fv','i','rh','rl','rp','rm','c (all)','nan'],
    'GarageCars': [],
    'FireplaceQu': ['ex','gd','ta','fa','po','na','nan'],
    'EnclosedPorch': [],
    'Id': [],
    'GarageCond': ['ex','gd','ta','fa','po','na','nan']
    }
  [cat.reverse() for cat in categories.values()] # so nan -> 0
  return categories
